export const DEPLOYMENT_FETCH = "DEPLOYMENT_FETCH";
export const DEPLOYMENT_FETCH_SUCCESS = "DEPLOYMENT_FETCH_SUCCESS";
export const DEPLOYMENT_FETCH_START = "DEPLOYMENT_FETCH_START";
export const DEPLOYMENT_FETCH_FAIL = "DEPLOYMENT_FETCH_FAIL";

export const DEPLOYMENT_ADD = "DEPLOYMENT_ADD";
export const DEPLOYMENT_ADD_START = "DEPLOYMENT_ADD_START";
export const DEPLOYMENT_ADD_SUCCESS = "DEPLOYMENT_ADD_SUCCESS";
export const DEPLOYMENT_ADD_FAIL = "DEPLOYMENT_ADD_FAIL";

export const DEPLOYMENT_UPDATE = "DEPLOYMENT_UPDATE";
export const DEPLOYMENT_UPDATE_START = "DEPLOYMENT_UPDATE_START";
export const DEPLOYMENT_UPDATE_SUCCESS = "DEPLOYMENT_UPDATE_SUCCESS";
export const DEPLOYMENT_UPDATE_FAIL = "DEPLOYMENT_UPDATE_FAIL";

export const DEPLOYMENT_REMOVE = "DEPLOYMENT_REMOVE";
export const DEPLOYMENT_REMOVE_START = "DEPLOYMENT_REMOVE_START";
export const DEPLOYMENT_REMOVE_SUCCESS = "DEPLOYMENT_REMOVE_SUCCESS";
export const DEPLOYMENT_REMOVE_FAIL = "DEPLOYMENT_REMOVE_FAIL";
